name: gettext-context
services:
  appserver:
    type: php:custom
    via: cli
    overrides:
      image: slimdeluxe/php:7.4
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    # For some reason, "composer test" does not work for this package, so we use the PHPUnit binary directly
    cmd: "php vendor/bin/phpunit"
