name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  LANG: "sl_SI.utf8"

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.4, 8.0, 8.1 ]

    name: ${{ matrix.os }} / PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up system locale
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y locales
        sudo locale-gen ${{ env.LANG }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: gettext

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --prefer-stable

    - name: Run test suite
      run: vendor/bin/phpunit
